# Generated by Django 4.0.2 on 2022-04-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.IntegerField(default=0, verbose_name='online'),
        ),
    ]
